const fs = require("fs");
const path = "src/hooks/useAnalyticsData.ts";
const lines = fs.readFileSync(path, "utf8").split(/\r?\n/);
lines.splice(529, 0,
  "",
  "function extractHostname(value?: string | null) {",
  "  if (!value) return '';",
  "  try {",
  "    return new URL(value).hostname.replace(/^www\\./, '').toLowerCase();",
  "  } catch {",
  "    return value.replace(/^https?:\\/\\//, '').replace(/^www\\./, '').split(/[\\/?#]/)[0]?.toLowerCase() || '';",
  "  }",
  "}",
  "",
  "function prettySourceLabel(value: string) {",
  "  return value",
  "    .replace(/^www\\./, '')",
  "    .replace(/[-_]+/g, '' '')",
  "    .replace(/\\s+/g, '' '')",
  "    .trim()",
  "    .replace(/\\b\\w/g, (char) => char.toUpperCase());",
  "}",
  "",
  "function normalizeSourceLabel(job: any) {",
  "  const rawSource = typeof job?.source_type === ''string'' ? job.source_type.trim() : '';",
  "  const fromUrl =",
  "    extractHostname(job?.apply_url) ||",
  "    extractHostname(job?.raw_data?.apply_url) ||",
  "    extractHostname(job?.raw_data?.job_url) ||",
  "    extractHostname(job?.raw_data?.source_url) ||",
  "    extractHostname(job?.raw_data?.url);",
  "  if (rawSource && rawSource.includes(''.'')) return rawSource.toLowerCase();",
  "  if (fromUrl) return fromUrl;",
  "  if (rawSource) return prettySourceLabel(rawSource);",
  "  return ''Unknown'';",
  "}",
  "",
  "function indexedColor(index: number) {",
  "  const palette = [''#1dff00'', ''#56c2ff'', ''#f59e0b'', ''#fb7185'', ''#a78bfa'', ''#14b8a6''];",
  "  return palette[index % palette.length];",
  "}",
);
