import { Download, RefreshCw, Search, SlidersHorizontal, UsersRound } from "lucide-react";
import { useMemo, useState } from "react";
import { useAdminUsageAnalytics, type UsageRange } from "../hooks/useAdminUsageAnalytics";
import { money, SourceBadge, UsagePanel, UsageStatCard } from "../components/usage/UsagePrimitives";

const ranges: { label: string; value: UsageRange }[] = [{ label: "Today", value: "today" }, { label: "7 Days", value: "7d" }, { label: "30 Days", value: "30d" }, { label: "90 Days", value: "90d" }, { label: "Billing period", value: "billing" }];
const pct = (value: number) => `${Math.round(Number(value || 0))}%`;

export default function AdminUserUsage() {
  const [range, setRange] = useState<UsageRange>("30d"); const [search, setSearch] = useState(""); const [plan, setPlan] = useState("all");
  const filters = useMemo(() => ({ range, search, plan, limit: 50, offset: 0 }), [range, search, plan]);
  const { data, loading, error, refresh } = useAdminUsageAnalytics("users", filters);
  const rows = data.users || []; const overview = data.overview || {};
  const exportCsv = () => { const header = ["User", "Plan", "AI consumed", "AI allocation", "Credits consumed", "Risk"]; const values = rows.map((row: any) => [row.email || row.user_id, row.plan, money(row.ai_consumed_nanos), money(row.ai_allocation_nanos), row.credits_consumed || 0, row.risk]); const blob = new Blob([[header, ...values].map((line) => line.map(String).map((x) => `\"${x.replaceAll('\"', '\"\"')}\"`).join(",")).join("\n")], { type: "text/csv" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = "jobraker-user-usage.csv"; a.click(); URL.revokeObjectURL(url); };
  return <div className="space-y-6">
    <div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><div className="mb-3 inline-flex items-center gap-2 rounded-full border border-brand/20 bg-brand/10 px-3 py-1 text-xs font-bold text-brand"><UsersRound className="h-3.5 w-3.5" />Private financial telemetry</div><h1 className="text-3xl font-bold text-white">User Usage</h1><p className="mt-2 max-w-2xl text-gray-400">Monitor AI consumption, Credits, providers and subscription limits across every account.</p></div><div className="flex flex-wrap gap-2 rounded-xl border border-brand/20 bg-black/30 p-1.5">{ranges.map((item) => <button key={item.value} onClick={() => setRange(item.value)} className={`rounded-lg px-3 py-2 text-xs font-semibold ${range === item.value ? "bg-brand text-black" : "text-gray-400 hover:bg-white/5 hover:text-white"}`}>{item.label}</button>)}</div></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><UsageStatCard label="Active users" value={overview.active_users || 0} /><UsageStatCard label="AI provider cost" value={money(overview.ai_provider_cost_nanos)} /><UsageStatCard label="Credits consumed" value={overview.credits_consumed || 0} /><UsageStatCard label="Above 80%" value={overview.users_above_80 || 0} tone="warning" /><UsageStatCard label="Expired with usage" value={overview.expired_with_usage || 0} tone="danger" /><UsageStatCard label="Reconciliation" value={overview.reconciliation_events || 0} tone="warning" /></div>
    <UsagePanel title="Account consumption" subtitle="Server-paginated and filtered. Private event contents never leave the protected endpoint."><div className="flex flex-col gap-3 border-b border-brand/10 p-4 lg:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-3.5 h-4 w-4 text-gray-500" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search email or user ID" className="w-full rounded-xl border border-gray-800 bg-black px-10 py-2.5 text-sm text-white outline-none focus:border-brand" /></label><select value={plan} onChange={(event) => setPlan(event.target.value)} className="rounded-xl border border-gray-800 bg-black px-3 py-2.5 text-sm text-gray-300"><option value="all">All plans</option><option>Free</option><option>Starter</option><option>Basics</option><option>Pro</option><option>Ultimate</option></select><button onClick={() => refresh()} className="inline-flex items-center justify-center gap-2 rounded-xl border border-brand/30 px-4 py-2.5 text-sm font-semibold text-brand"><RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`} />Refresh</button><button onClick={exportCsv} className="inline-flex items-center justify-center gap-2 rounded-xl bg-brand px-4 py-2.5 text-sm font-bold text-black"><Download className="h-4 w-4" />Export safe CSV</button></div>
      {error && <p className="m-4 rounded-xl border border-rose-400/30 bg-rose-400/10 p-3 text-sm text-rose-100">{error}</p>}
      <div className="overflow-x-auto"><table className="w-full min-w-[1120px] text-sm"><thead className="bg-white/[0.02] text-left text-xs uppercase tracking-wider text-gray-500"><tr>{["User", "Plan", "Subscription", "AI allocation", "AI used", "24h", "Tokens", "Composio", "Credits", "Providers", "Risk"].map((cell) => <th key={cell} className="px-4 py-3 font-semibold">{cell}</th>)}</tr></thead><tbody className="divide-y divide-gray-900">{rows.map((row: any) => <tr key={row.user_id} className="hover:bg-brand/[0.035]"><td className="sticky left-0 bg-background px-4 py-4 text-white"><p className="font-semibold">{row.email || "Hidden account"}</p><p className="font-mono text-[11px] text-gray-600">{row.user_id}</p></td><td className="px-4 py-4 text-gray-300">{row.plan || "Free"}</td><td className="px-4 py-4 text-gray-400">{row.subscription_status || "inactive"}</td><td className="px-4 py-4 text-gray-300">{money(row.ai_allocation_nanos)}</td><td className="px-4 py-4"><p className="font-medium text-white">{money(row.ai_consumed_nanos)}</p><p className="text-xs text-gray-500">{pct(row.ai_percent)}</p></td><td className="px-4 py-4 text-gray-300">{pct(row.ai_24h_percent)}</td><td className="px-4 py-4 text-gray-300">{Number(row.input_tokens || 0).toLocaleString()} / {Number(row.output_tokens || 0).toLocaleString()}</td><td className="px-4 py-4 text-gray-300">{row.composio_calls || 0}</td><td className="px-4 py-4 text-gray-300">{row.credits_available || 0} available<br /><span className="text-xs text-gray-500">{row.credits_consumed || 0} used</span></td><td className="px-4 py-4"><SourceBadge source={row.usage_source} /></td><td className="px-4 py-4"><span className={`rounded-full px-2 py-1 text-xs font-bold ${row.risk === "high" ? "bg-rose-400/10 text-rose-200" : row.risk === "watch" ? "bg-amber-300/10 text-amber-100" : "bg-emerald-400/10 text-emerald-200"}`}>{row.risk || "normal"}</span></td></tr>)}{!loading && rows.length === 0 && <tr><td colSpan={11} className="px-4 py-16 text-center text-gray-500">No matching usage records for this period.</td></tr>}</tbody></table></div></UsagePanel>
  </div>;
}
