import { Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { RefreshCw, TrendingUp } from "lucide-react";
import { useAdminUsageAnalytics } from "../hooks/useAdminUsageAnalytics";
import { money, SourceBadge, UsagePanel, UsageStatCard } from "../components/usage/UsagePrimitives";

export default function AdminCostAllocation() {
  const { data, loading, error, refresh } = useAdminUsageAnalytics("plan_economics", { range: "30d" }); const overview = data.overview || {}; const plans = data.planEconomics || []; const providers = data.providerEconomics || [];
  return <div className="space-y-6"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><div className="mb-3 inline-flex items-center gap-2 rounded-full border border-brand/20 bg-brand/10 px-3 py-1 text-xs font-bold text-brand"><TrendingUp className="h-3.5 w-3.5" />Unit economics control room</div><h1 className="text-3xl font-bold text-white">Cost Allocation</h1><p className="mt-2 text-gray-400">Compare internal plan allocations with real AI and provider consumption.</p></div><button onClick={() => refresh()} className="inline-flex items-center justify-center gap-2 rounded-xl border border-brand/30 px-4 py-2.5 font-semibold text-brand"><RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`} />Refresh live totals</button></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><UsageStatCard label="Subscription revenue" value={money(overview.subscription_revenue_nanos)} /><UsageStatCard label="Actual AI cost" value={money(overview.ai_actual_cost_nanos)} /><UsageStatCard label="Provider cost" value={money(overview.provider_actual_cost_nanos)} /><UsageStatCard label="Gross contribution" value={money(overview.contribution_nanos)} tone={Number(overview.contribution_nanos || 0) < 0 ? "danger" : "brand"} /></div>
    {error && <p className="rounded-xl border border-rose-400/30 bg-rose-400/10 p-3 text-sm text-rose-100">{error}</p>}
    <div className="grid gap-6 xl:grid-cols-2"><UsagePanel title="Allocation versus actual cost" subtitle="Separate AI allowance from external-provider allocation."><div className="h-80 p-4"><ResponsiveContainer width="100%" height="100%"><BarChart data={plans}><CartesianGrid strokeDasharray="3 3" stroke="#24322a" /><XAxis dataKey="plan" stroke="#77827d" /><YAxis tickFormatter={(v) => `$${Number(v) / 1e9}`} stroke="#77827d" /><Tooltip formatter={(v: number) => money(v)} /><Legend /><Bar dataKey="ai_allocation_nanos" name="AI allocation" fill="#2fd968" radius={[5, 5, 0, 0]} /><Bar dataKey="actual_ai_cost_nanos" name="Actual AI cost" fill="#8b9b91" radius={[5, 5, 0, 0]} /><Bar dataKey="provider_allocation_nanos" name="Provider allocation" fill="#2b7b49" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></div></UsagePanel>
      <UsagePanel title="Provider composition" subtitle="Confirmed and estimated usage stay explicitly distinct."><div className="divide-y divide-gray-900">{providers.map((provider: any) => <div key={provider.provider} className="flex items-center justify-between gap-4 p-5"><div><p className="font-bold capitalize text-white">{provider.provider}</p><p className="mt-1 text-xs text-gray-500">{Number(provider.units || 0).toLocaleString()} units · {provider.credits_charged || 0} user credits</p></div><div className="text-right"><p className="font-semibold text-white">{money(provider.provider_cost_nanos)}</p><SourceBadge source={provider.usage_source} /></div></div>)}{providers.length === 0 && <p className="p-10 text-center text-gray-500">No provider events in this period.</p>}</div></UsagePanel></div>
    <UsagePanel title="Plan economics" subtitle="Basics is intentionally displayed as $5 AI allocation and $5 provider allocation."><div className="overflow-x-auto"><table className="w-full min-w-[1060px] text-sm"><thead className="bg-white/[0.02] text-left text-xs uppercase tracking-wider text-gray-500"><tr>{["Plan", "Subscribers", "Revenue", "AI allocation", "AI actual", "Provider allocation", "Provider actual", "Total actual", "Contribution", "Risk"].map((c) => <th key={c} className="px-4 py-3">{c}</th>)}</tr></thead><tbody className="divide-y divide-gray-900">{plans.map((plan: any) => <tr key={plan.plan} className="hover:bg-brand/[0.035]"><td className="px-4 py-4 font-bold text-white">{plan.plan}</td><td className="px-4 py-4 text-gray-300">{plan.active_subscribers || 0}</td><td className="px-4 py-4 text-gray-300">{money(plan.revenue_nanos)}</td><td className="px-4 py-4 text-gray-300">{money(plan.ai_allocation_nanos)}</td><td className="px-4 py-4 text-gray-300">{money(plan.actual_ai_cost_nanos)}</td><td className="px-4 py-4 text-gray-300">{money(plan.provider_allocation_nanos)}</td><td className="px-4 py-4 text-gray-300">{money(plan.provider_actual_cost_nanos)}</td><td className="px-4 py-4 font-semibold text-white">{money(plan.total_actual_cost_nanos)}</td><td className="px-4 py-4 text-gray-300">{money(plan.contribution_nanos)}</td><td className="px-4 py-4"><SourceBadge source={plan.risk === "over" ? "reconciliation required" : "confirmed"} /></td></tr>)}</tbody></table></div></UsagePanel>
  </div>;
}
