name: supabase-push

on:
  workflow_dispatch:

jobs:
  push-migrations:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm i -g supabase@^2
      - name: Supabase login
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: supabase login --token "${SUPABASE_ACCESS_TOKEN}"
      - name: Link project
        env:
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        working-directory: backend/supabase
        run: supabase link --project-ref "${SUPABASE_PROJECT_REF}" --password "${SUPABASE_DB_PASSWORD}" --yes
      - name: Push migrations (dry-run)
        working-directory: backend/supabase
        run: supabase db push --linked --dry-run
      - name: Push migrations
        env:
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        working-directory: backend/supabase
        run: supabase db push --linked --include-all --yes -p "${SUPABASE_DB_PASSWORD}"
